### ISSUE TITLE
Elasticsearch 存快照到 Amazon S3 这一步有点小疑问。

### ISSUE THREAD

**Issue by cupen** [xtaci/log_analysis#1]
elasticearch 里数据为何要存到 S3？
S3 价格挺贵的呀 https://aws.amazon.com/cn/s3/pricing/

**Comment by xtaci** [comment]
那就存文件呗

**Comment by cupen** [comment]
哦。![ki3 g7x6npvizoznx 1bkeb](https://cloud.githubusercontent.com/assets/1221615/20745975/9d831656-b71e-11e6-9073-c6ebe7ee48b1.gif)
